# Generated by Django 4.2.6 on 2023-11-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
    ]
